version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgres://youruser:yourpassword@db:5432/yourdatabase
      JWT_SECRET: your_jwt_secret
      JWT_REFRESH_TOKEN_SECRET: your_refresh_token_secret
      RESEND_API_KEY: your_resend_api_key
      PASSWORD_SALT: "10"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
